# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf520ed6c757bbea945ef766e30f06c3135ab3cae6f288fab7831150b422a557aadf797a1d7e25a94e57dc5fa7d66d7811de4ab85354103d6a97ed523f23d16c

test:
  secret_key_base: 60094c822ee228932bc2caf07148d5a6a7f8669287b18710fbbdd4c6def6f00338c3cb8f21cfb4f8be481633dd694960bf189ae35ddd93aa66744b3bd31f0fa4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
